//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounts
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.FriendLinks = new HashSet<FriendLink>();
            this.FriendLinks1 = new HashSet<FriendLink>();
            this.Payments = new HashSet<Payment>();
            this.Payments1 = new HashSet<Payment>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<FriendLink> FriendLinks { get; set; }
        public virtual ICollection<FriendLink> FriendLinks1 { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Payment> Payments1 { get; set; }
    }
}
